### ISSUE TITLE
Outbound link tracking breaks links when Ghostery is running 

### ISSUE THREAD

**Issue by steam** [Zewo/zewo.github.io#2]
Visiting zewo.io with Ghostery enabled results in a non-functioning main navigation.

**Comment by steam** [comment]
The outbound link tracking also breaks links when using Purify in Mobile Safari.

**Comment by steam** [comment]
It looks like the main project is used for issues. Let me know if I should close this and recreate it over there.

**Comment by paulofaria** [comment]
I'm really sad about this. We're not tracking people's clicks to spy on their lives. We just want to build a good experience. Have any suggestions on how to go about this?

**Comment by rabc** [comment]
What do you mean by main navigation? tried to navigate with Ghostery enabled but everything seems fine.

Although it could be a problem because of Mouseflow (this kind of stuff always break websites).

**Comment by paulofaria** [comment]
I know ublock blocks google analytics link tracking. AdBlock works fine on safari OSX here.

**Comment by steam** [comment]
Thanks for the quick response. I verified that Chrome and Safari on El Capitan prevent the `Github` `Docs` `Blog` `Slack` `Twitter` and `Contact` links from working. I verified that enabling the google analytics script fixes the links. The links work when leaving the Facebook Connect script and Mouseflow script disabled while enabling the GA script.

**Comment by steam** [comment]
http://veithen.github.io/2015/01/24/outbound-link-tracking.html looks to have work around for this issue. The broken links are likely due to Ghostery preventing analytics.js from loading.

**Comment by Danappelxx** [comment]
Looks like ublock block google analytics as well. It should be fairly trivial to detect is google analytics is blocked, and at that point we should just be able to redirect.

**Comment by paulofaria** [comment]
```js
var trackOutboundLink = function(url) {
  if (ga.q) {
    // Google Analytics is blocked
    document.location = url;
  } else {
    ga("send", "event", "outbound", "click", url, {"hitCallback":
      function () {
        document.location = url;
      }
    });
  }
}
```

**Comment by paulofaria** [comment]
Maybe we should go for his suggestion in the end of the article:

```html
<a href="http://example.com" class="tracked">...</a>
```

```js
$(function() {
  $("a.tracked").click(function(e) {
    if (!ga.q) {
      var url = $(this).attr("href");
      ga("send", "event", "outbound", "click", url, {"hitCallback":
        function () {
          document.location = url;
        }
      });
      e.preventDefault();
    }
  });
});
```

are we using JQuery already?

**Comment by Danappelxx** [comment]
I took the simpler approach for now. We can use jQuery for this later.

**Comment by paulofaria** [comment]
@steam can you test please?

**Comment by steam** [comment]
Looks great @paulofaria, the links work with Ghostery running, thanks!

**Comment by paulofaria** [comment]
:metal: beautiful!
